### ISSUE TITLE
Moving image does not exit

### ISSUE THREAD

**Issue by aalfi** [gfolego/alzheimers#1]
alfin@dgxa100:$ docker-compose run --rm  adnet-brain /path/T1w_norm.nii.gz   `Path`tag.nii.gz. 
Creating alzheimers_adnet-brain_run ... done
Args: Namespace(image='/path/T1w_norm.nii.gz', output='path/tag.nii.gz.')
---------------------  Running brain_process.sh on 52b9675a5f65  ---------------------
Cleanup: rm -rfv /tmp/tmp.bYXW5QaaM1/
removed directory: '/tmp/tmp.bYXW5QaaM1/'
BEGIN >>>>>>>>>>>>>>>>>>>>
mkdir -pv /tmp/tmp.bYXW5QaaM1/
mkdir: created directory '/tmp/tmp.bYXW5QaaM1/'
END   <<<<<<<<<<<<<<<<<<<<
 Done in  0h 0m 0s

**

> Moving image '/path/T1w_norm.nii.gz' does not exist.  See usage: '/repo/src/brain_process.sh -h 1

**
Done!

**Comment by gfolego** [comment]
Hi @aalfi ,
This problem happens because the docker-compose file only maps the repository directory.
If the file is outside this directory, you'll need to map it as well.

In your case, this should work:
```bash
docker-compose run --rm -v /path:/path adnet-brain /path/T1w_norm.nii.gz /path/tag.nii.gz
```

Please let me know how it goes.
Thanks!

**Comment by aalfi** [comment]
Thank you Mr. Folego!
I am a rookie in coding. Each process in a docker is so convenient.
your library is one of the best ones for AD classification
I got the preprocessed nifti file!
wish you success!
